// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHP-PeG-wlDP8v1FCinojG5Azh4rg7BSk',
    appId: '1:696315010133:web:c0a6f3698c6746dfdb08dc',
    messagingSenderId: '696315010133',
    projectId: 'elabs-3fde5',
    authDomain: 'elabs-3fde5.firebaseapp.com',
    storageBucket: 'elabs-3fde5.firebasestorage.app',
    measurementId: 'G-47QHH7B1LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsQDZznO-a3CJrfu1VWmlP01DxuJqnPBA',
    appId: '1:696315010133:android:9f4d906291143804db08dc',
    messagingSenderId: '696315010133',
    projectId: 'elabs-3fde5',
    storageBucket: 'elabs-3fde5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcC7mDSahH_KbgkTqNRZfwOaeMn05AZBA',
    appId: '1:696315010133:ios:fb8b7288d296eb3fdb08dc',
    messagingSenderId: '696315010133',
    projectId: 'elabs-3fde5',
    storageBucket: 'elabs-3fde5.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );
}
